name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branches
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  run-linters:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_ACTIONS_BOT_PAT }}

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run ESLint
        run: npx --no-install eslint --ext .js --fix --no-color --format json  "."

      - name: Set up git credentials
        run: |
          git config --global user.email "weee-open-bot@users.noreply.github.com"
          git config --global user.name "weee-open-bot"

      - name: Commit and push changes
        run: |
          git commit -am "Fix code style issues with ESLint" && git push || echo "No changes to commit"
